export const ADD_TEAM = "ADD_TEAM";
export const REM_TEAM = "REM_TEAM";

export const ADD_SCHED_SERVICE = "ADD_SCHED_SERVICE";
export const REM_SCHED_SERVICE = "ADD_SCHED_SERVICE";

export const ADD_TEAM_SERVICE = "ADD_TEAM_SERVICE";
export const REM_TEAM_SERVICE = "REM_TEAM_SERVICE";
export const REORDER_SERVICE = "REORDER_SERVICE";
